<?php

/**
 * @file
 * A block module that displays a contact form.
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function accesibilidadweb_contact_form_help($path, $arg) {
  switch ($path) {
    case "admin/help#accesibilidadweb_contact_form":
      return t("Displays contact form"); 
      break; 
  }
}

/**
 * Implements hook_theme().
 */
function accesibilidadweb_contact_form_theme($existing, $type, $theme, $path) {
  return array(
    'accesibilidadweb_contact_form_block' => array(
      'variables' => array('title' => NULL, 'form' => NULL),
      'path' => drupal_get_path('module', 'accesibilidadweb_contact_form') . '/templates/',
      'template' => 'accesibilidadweb-contact-form-block'
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function accesibilidadweb_contact_form_block_info() {
  $blocks['accesibilidadweb_contact_form'] = array(
    // The name that will appear in the block list.
    'info' => t('Accesibilidad Web Contact Form'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Implements hook_menu().
 */
function accesibilidadweb_contact_form_menu() {
  $items['accesibilidadweb_contact_form'] = array(
    'title' => 'Accesibilidad Web Contact Form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('accesibilidadweb_contact_form'),
    'access arguments' => array('access site-wide contact form'),
    'access callback' => TRUE,
    'type' => MENU_SUGGESTED_ITEM,
  );
}

/**
 * Implements hook_mail().
 */
function accesibilidadweb_contact_form_mail($key, &$message, $params) {
  switch ($key) {
    case 'tanta_mail':
      $message['subject'] .= t('Contacto desde la accesibilidadweb.com');
      $message['body'][] = t('Nombre: '.$params['name']);
      $message['body'][] = t('Teléfono: '.$params['phone']);
      $message['body'][] = t('Compañía: '.$params['company']);
      $message['body'][] = t('Mensaje: '.$params['message']);
      break;
  }
}

/**
 * Implements hook_block_view().
 */
function accesibilidadweb_contact_form_block_view($delta = '') {
  $block = array();
  if ('accesibilidadweb_contact_form' === $delta) {
    $block['subject'] = t('¿Qué necesitas?');
    $accesibilidadweb_contact_form = drupal_get_form('accesibilidadweb_contact_form');
    $block['content'] = theme(
      'accesibilidadweb_contact_form_block',
      array(
        'title' => $block['subject'],
        'form' => render($accesibilidadweb_contact_form),
      )
    );
  }
  return $block;
}

/**
 * Form constructor for accesibilidad web contact form
 * 
 * @see accesibilidadweb_contact_form_validate()
 * @see accesibilidadweb_contact_form_submit()
 */
function accesibilidadweb_contact_form($form, &$form_state) {
  // Provide a text field.
  $form['name'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#attributes' => array ('class' => array ('form-control'), 'placeholder' => t('Tu nombre')),
    '#prefix' => '<div class="form-group">',
    '#suffix' => '</div>',
    '#title' => t('Tu nombre'),
    '#validate' => array(
      'required' => array(true),
    ),
  );
  $form['email'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#attributes' => array ('class' => array ('form-control'), 'placeholder' => t('Tu email')),
    '#prefix' => '<div class="form-group">',
    '#suffix' => '</div>',
    '#title' => t('Tu email'),
    '#validate' => array(
      'email' => array(true),
      'required' => array(true),
    ),
  );
  $form['phone'] = array(
    '#type' => 'textfield',
    '#required' => FALSE,
    '#attributes' => array ('class' => array ('form-control'), 'placeholder' => t('Tu teléfono')),
    '#prefix' => '<div class="form-group">',
    '#suffix' => '</div>',
    '#title' => t('Tu teléfono'),
    '#validate' => array(
      'minlength' => array(9)
    ),
  );
  $form['company'] = array(
    '#type' => 'textfield',
    '#required' => FALSE,
    '#attributes' => array ('class' => array ('form-control'), 'placeholder' => t('Tu empresa')),
    '#prefix' => '<div class="form-group">',
    '#suffix' => '</div>',
    '#title' => t('Tu empresa'),
  );
  $form['message'] = array(
    '#type' => 'textarea',
    '#required' => FALSE,
    '#required' => TRUE,
    '#attributes' => array ('class' => array ('form-control'), 'placeholder' => t('Tu mensaje')),
    '#prefix' => '<div class="form-group">',
    '#suffix' => '</div>',
    '#title' => t('Tu mensaje'),
    '#validate' => array(
      'required' => array(true),
    ),
  );
  
  // Provide a submit button.
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Enviar'),
    '#attributes' => array ('class' => array ('btn', 'btn-success', 'btn-block')),
  );

  $form['#client_validation'] = TRUE;
  
  return $form;
}

/**
 * Form validation handler for accesibilidadweb_contact_form().
 *
 * @see accesibilidadweb_contact_form_submit()
 */
function accesibilidadweb_contact_form_validate($form, &$form_state) {
  if (!valid_email_address($form_state['values']['email'])) {
    form_set_error('email', t('Debe indicar un email váĺido.'));
  }
}

/**
 * Form submission handler for accesibilidadweb_contact_form().
 *
 * @see accesibilidadweb_contact_form_validate()
 */
function accesibilidadweb_contact_form_submit($form, &$form_state) {
  global $language;

  $fields = array (
    'name' => $form_state['values']['name'],
    'email' => $form_state['values']['email'], 
    'phone' => $form_state['values']['phone'],
    'company' => $form_state['values']['company'],
    'message' => $form_state['values']['message']
  );

  drupal_mail('accesibilidadweb_contact_form', 'tanta_mail', 'david.abad@tantacom.com', $language, $fields, 'customer.service@tantacom.com');

  drupal_set_message(t('El formulario ha sido enviado.'));
}
